export enum repositories {
    USER = 'USER_REPOSITORY',
    MOVIE = 'MOVIE_REPOSITORY',
    PLANET = 'PLANET_REPOSITORY',
    SPECIE = 'SPECIE_REPOSITORY',
    STARSHIP = 'STARSHIP_REPOSITORY',
    VEHICLE = 'VEHICLE_REPOSITORY',
    CHARACTER = 'CHARACTER_REPOSITORY',
};